# -*- coding: utf-8 -*-
"""API_Flask_JSON_DIO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GNPXowVmj2bhf2ViMHgrqFignP4tsLEe
"""

!pip install flask_ngrok

import pandas as pd
from flask_ngrok import run_with_ngrok
from flask import request, jsonify, Flask
import random as rk

app = Flask(__name__)
run_with_ngrok(app)

d = {
    "name": "Nikolas",
    "surname": "Tesla",
    "idade": 60
}

@app.route('/')

def home():
  '''
  The entire line below must be written in a single line.
  '''
  return "<marquee><h3>"

@app.route("/input") #code to assign Input URL in our app to function input.

def input():
  return jsonify(d) # "d" is the dictionary we defined

@app.route("/output", methods=['GET', 'POST'])

def prodJson():
  pred = r.choice(['positive', 'negative'])
  nd = d
  nd["prediction"]=pred
  return jsonify(nd)

  app.run()