# -*- coding: utf-8 -*-
"""Cópia de Primeiro-Passo-Django-DIO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SWeRnY05SK6E2MPY98kA_l6yuDxuHqSJ
"""

!pip install django

!pip install flask
!pip install flask-ngrok

from flask import *
from flask_ngrok import run_with_ngrok
app = Flask(__name__)
@app.route('/index')
def home():
  return 'Hello World'

run_with_ngrok(app)
app.run()

!pip install fastapi nest-asyncio pyngrok uvicorn

from fastapi import FastAPI
import nest_asyncio
from pyngrok import ngrok
import uvicorn

app = FastAPI()

@app.get('\index')
async def home():
  return 'Hello World'

ngrok_tunnel = ngrok.connect(8000)
print('Public URL', ngrok_tunnel.public_url)
nest_asyncio.apply()
uvicorn.run(app, port=8000)